# 1.- CONSTRUIR LA IMAGEN DOCKER EN UN CONTENEDOR LIMPIO PARA ASEGURAR QUE EL AMBIENTE SE PUEDE RECREAR SIN PROBLEMAS
FROM node:16-alpine as build-stage
LABEL version="1.0"
LABEL maintainer="barahonachrism@yahoo.es"

#DIRECTORIO DONDE VAMOS A COMPILAR TODO EL PROYECTO
WORKDIR /app
#COPIAR TODOS LOS MICROFRONTENDS A LA CARPETA /app DEL CONTENEDOR
COPY . .

# CONSTRUIR EL PROYECTO CONTENEDOR DE LA APLICACION
RUN npm install && npm run build

#2.- CONSTRUIR LA IMAGEN DOCKER COPIANDO LOS DIRECTORIOS DIST DE CADA MICROFRONTEND USANDO NGINX
FROM nginx:1.21.0

# COPIAR LA CARPETA BUILD COMPILADA DEL FRONTEND GENERADA POR EL CONTENEDOR ANTERIOR
COPY --from=build-stage /app/build /usr/share/nginx/html

#COPIAR ARCHIVO DE CONFIGURACION DE NGINX PARA PROXIFICAR LAS PETICIONES HACIA LOS MICROSERVICIOS ASEGURADOS
COPY ./nginx.conf /etc/nginx/nginx.conf